### ISSUE TITLE
cmake dependency

### ISSUE THREAD

**Issue by rds76** [pycompression/python-zlib-ng#19]
Setup uses option for cmake `-j` but this is avail since version 3.12 of cmake, but required version for zlib-ng is 3.5.1+ `CMake 3.5.1 or higher is required`

**Comment by rds76** [comment]
I cannot build this lib with older but supported cmake, if -j option is used for cmake, zlib-ng build fails

**Comment by rhpvorderman** [comment]
You can build zlib-ng separately, then point the setup to it:
```bash
export PYTHON_ZLIB_NG_BUILD_CACHE=1
export PYTHON_ZLIB_NG_BUILD_CACHE_FILE=/tmp/build_cache
# Compile zlib-ng in some directory
echo some_directory > "$PYTHON_ZLIB_NG_BUILD_CACHE_FILE"
pip install zlib-ng
```
That should do the trick.

**Comment by rds76** [comment]
thats what I tried before I raise this issue
`PYTHON_ZLIB_NG_BUILD_CACHE=1 PYTHON_ZLIB_NG_BUILD_CACHE_FILE=/tmp/.zlcache pip3 install zlib-ng==0.2.0` but it still tries to build zlib-ng (cache file points to already built zlib-ng folder)

**Comment by rhpvorderman** [comment]
Thanks for reporting back. Can this issue be closed?

**Comment by rhpvorderman** [comment]
From 0.3.0 onwards, cmake is no longer required to build for linux.
