### ISSUE TITLE
Internal API _PyBytes_Join() is removed in Python 3.13

### ISSUE THREAD

**Issue by musicinmybrain** [pycompression/python-zlib-ng#30]
The internal CPython API function `_PyBytes_Join()` is removed in Python 3.13. You will need to find a substitute.

The most straightforward workaround is to just call the Python `bytes.join` method on the empty bytestring object we already have. Since this call happens only once at the end of `GzipReader_readall`, I suspect any added overhead should be negligible. I’ve tested this fix and will follow up with a PR.

See downstream Fedora Linux bug https://bugzilla.redhat.com/show_bug.cgi?id=2259627.

See also CPython issue https://github.com/python/cpython/issues/106320 and specifically https://github.com/python/cpython/pull/107144.

**Comment by rhpvorderman** [comment]
Let me think about this for a bit. The alternative is to use _PyBytes_Resize on a bytes object. 

Thanks for reporting the issue.

**Comment by musicinmybrain** [comment]
> Let me think about this for a bit. The alternative is to use _PyBytes_Resize on a bytes object.

OK! Since `_PyBytes_Resize` is [documented](https://docs.python.org/dev/c-api/bytes.html#c._PyBytes_Resize), it is safe from this round of API removals even though it’s “private.”
